<?xml version="1.0" encoding="UTF-8"?>
<robot generator="Robot 6.1.1 (Python 3.12.0 on darwin)" generated="20231127 17:29:25.458" rpa="false" schemaversion="4">
<suite id="s1" name="Tests" source="/Users/maxxof/Desktop/HY/ohtu/miniprojekti/src/tests">
<suite id="s1-s1" name="References" source="/Users/maxxof/Desktop/HY/ohtu/miniprojekti/src/tests/references.robot">
<test id="s1-s1-t1" name="Add Book Reference with valid input" line="8">
<kw name="Input Add Reference Command" library="resource" type="SETUP">
<kw name="Input" library="ReferencesLibrary">
<arg>"0"</arg>
<msg timestamp="20231127 17:29:46.569" level="FAIL">Initializing library 'ReferencesLibrary' with no arguments failed: IndexError: pop from empty list
Traceback (most recent call last):
  File "/Users/maxxof/Desktop/HY/ohtu/miniprojekti/src/ReferencesLibrary.py", line 12, in __init__
    self._references = References(self._io, self.reference_service, None)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/maxxof/Desktop/HY/ohtu/miniprojekti/src/references.py", line 11, in __init__
    self.welcome(io_handler, service)
  File "/Users/maxxof/Desktop/HY/ohtu/miniprojekti/src/references.py", line 23, in welcome
    command = io_handler.read("What do you want to do? ")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/maxxof/Desktop/HY/ohtu/miniprojekti/src/tests/references_test.py", line 14, in read
    return self.inputs.pop(0)
           ^^^^^^^^^^^^^^^^^^
IndexError: pop from empty list</msg>
<status status="FAIL" starttime="20231127 17:29:42.542" endtime="20231127 17:29:46.569"/>
</kw>
<status status="FAIL" starttime="20231127 17:29:42.541" endtime="20231127 17:29:46.570"/>
</kw>
<status status="FAIL" starttime="20231127 17:29:42.539" endtime="20231127 17:29:46.571">Setup failed:
Initializing library 'ReferencesLibrary' with no arguments failed: IndexError: pop from empty list
Traceback (most recent call last):
  File "/Users/maxxof/Desktop/HY/ohtu/miniprojekti/src/ReferencesLibrary.py", line 12, in __init__
    self._references = References(self._io, self.reference_service, None)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/maxxof/Desktop/HY/ohtu/miniprojekti/src/references.py", line 11, in __init__
    self.welcome(io_handler, service)
  File "/Users/maxxof/Desktop/HY/ohtu/miniprojekti/src/references.py", line 23, in welcome
    command = io_handler.read("What do you want to do? ")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/maxxof/Desktop/HY/ohtu/miniprojekti/src/tests/references_test.py", line 14, in read
    return self.inputs.pop(0)
           ^^^^^^^^^^^^^^^^^^
IndexError: pop from empty list</status>
</test>
<status status="FAIL" starttime="20231127 17:29:25.464" endtime="20231127 17:29:46.572"/>
</suite>
<status status="FAIL" starttime="20231127 17:29:25.459" endtime="20231127 17:29:46.573"/>
</suite>
<statistics>
<total>
<stat pass="0" fail="1" skip="0">All Tests</stat>
</total>
<tag>
</tag>
<suite>
<stat pass="0" fail="1" skip="0" id="s1" name="Tests">Tests</stat>
<stat pass="0" fail="1" skip="0" id="s1-s1" name="References">Tests.References</stat>
</suite>
</statistics>
<errors>
</errors>
</robot>
